fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "anto.171961@gmail.com"
        sender_name: "Anthony Tacuri"
    